/**
 * VEMIO™ — GLPI API Helper
 *
 * Reusable GLPI REST API client for Vercel API routes.
 * All functions are best-effort — they log errors but never throw.
 * Alert state changes should always succeed even if GLPI is down.
 *
 * Auth: App-Token + user_token
 */

const GLPI_API_BASE = process.env.GLPI_API_BASE || 'https://techsupport.vinayenterprises.co.in/api.php/v1';
const GLPI_APP_TOKEN = process.env.GLPI_APP_TOKEN;
const GLPI_USER_TOKEN = process.env.GLPI_USER_TOKEN;

async function initSession() {
  const res = await fetch(`${GLPI_API_BASE}/initSession`, {
    method: 'GET',
    headers: {
      'App-Token': GLPI_APP_TOKEN,
      'Authorization': `user_token ${GLPI_USER_TOKEN}`,
      'Content-Type': 'application/json',
    },
  });
  if (!res.ok) throw new Error(`initSession ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return data.session_token;
}

async function killSession(token) {
  try {
    await fetch(`${GLPI_API_BASE}/killSession`, {
      method: 'GET',
      headers: { 'App-Token': GLPI_APP_TOKEN, 'Session-Token': token },
    });
  } catch { /* best effort */ }
}

async function glpiRequest(token, method, path, body = null) {
  const opts = {
    method,
    headers: {
      'App-Token': GLPI_APP_TOKEN,
      'Session-Token': token,
      'Content-Type': 'application/json',
    },
  };
  if (body) opts.body = JSON.stringify(body);
  const res = await fetch(`${GLPI_API_BASE}${path}`, opts);
  if (!res.ok) throw new Error(`${method} ${path} ${res.status}: ${await res.text()}`);
  return res.json();
}

// VEMIO tenant slug → GLPI entity ID
const ENTITY_MAP = { 'vinay-hq': 4, 'aia-engineering': 18 };

// VEMIO severity → GLPI priority (1=VeryLow..5=VeryHigh)
const SEVERITY_TO_PRIORITY = { critical: 5, high: 4, medium: 3, low: 2 };

/**
 * Create a GLPI ticket. Returns { ticketId, ticketUrl } or null.
 * NEVER throws — logs errors and returns null.
 */
export async function createGLPITicket({ title, description, severity, tenantSlug, alertType, deviceName, siteName }) {
  if (!GLPI_APP_TOKEN || !GLPI_USER_TOKEN) {
    console.warn('[GLPI] Missing tokens — skipping ticket creation');
    return null;
  }

  let session;
  try {
    session = await initSession();
    const entityId = ENTITY_MAP[tenantSlug] || 0;
    const priority = SEVERITY_TO_PRIORITY[severity] || 3;

    const descHtml = `
      <div style="font-family:sans-serif;font-size:13px;">
        <p><strong>VEMIO™ Alert</strong></p>
        <table style="border-collapse:collapse;margin:10px 0;">
          <tr><td style="padding:4px 12px 4px 0;color:#666;">Type</td><td>${alertType?.replace(/_/g, ' ') || '—'}</td></tr>
          <tr><td style="padding:4px 12px 4px 0;color:#666;">Severity</td><td><strong>${severity?.toUpperCase()}</strong></td></tr>
          ${deviceName ? `<tr><td style="padding:4px 12px 4px 0;color:#666;">Device</td><td>${deviceName}</td></tr>` : ''}
          ${siteName ? `<tr><td style="padding:4px 12px 4px 0;color:#666;">Site</td><td>${siteName}</td></tr>` : ''}
        </table>
        ${description || ''}
        <p style="color:#999;font-size:11px;margin-top:16px;">Generated by VEMIO™</p>
      </div>`.trim();

    const result = await glpiRequest(session, 'POST', '/Ticket', {
      input: { name: title, content: descHtml, priority, entities_id: entityId, type: 1, status: 2, urgency: priority, impact: priority >= 4 ? 4 : 3 },
    });

    console.log(`[GLPI] Created ticket #${result.id}: ${title}`);
    return { ticketId: result.id, ticketUrl: `https://techsupport.vinayenterprises.co.in/front/ticket.form.php?id=${result.id}` };
  } catch (err) {
    console.error('[GLPI] Ticket creation failed:', err.message);
    return null;
  } finally {
    if (session) await killSession(session);
  }
}

/**
 * Close/solve a GLPI ticket. Returns true or null.
 * NEVER throws.
 */
export async function closeGLPITicket(ticketId, resolutionNote) {
  if (!GLPI_APP_TOKEN || !GLPI_USER_TOKEN || !ticketId) return null;

  let session;
  try {
    session = await initSession();
    await glpiRequest(session, 'POST', `/Ticket/${ticketId}/ITILSolution`, {
      input: { itemtype: 'Ticket', items_id: ticketId, content: `<div style="font-family:sans-serif;font-size:13px;">${resolutionNote}</div>`, status: 5 },
    });
    console.log(`[GLPI] Closed ticket #${ticketId}`);
    return true;
  } catch (err) {
    console.error(`[GLPI] Failed to close #${ticketId}:`, err.message);
    return null;
  } finally {
    if (session) await killSession(session);
  }
}