/**
 * VEMIO™ — GLPI API Helper
 *
 * Reusable GLPI REST API client for Vercel API routes.
 * Creates tickets, adds followups, closes tickets.
 *
 * Auth: App-Token + user_token (same as GLPI worker)
 * GLPI API: https://techsupport.vinayenterprises.co.in/api.php/v1
 */

const GLPI_API_BASE = process.env.GLPI_API_BASE || 'https://techsupport.vinayenterprises.co.in/api.php/v1';
const GLPI_APP_TOKEN = process.env.GLPI_APP_TOKEN;
const GLPI_USER_TOKEN = process.env.GLPI_USER_TOKEN;

/**
 * Initialize a GLPI session. Returns session_token.
 * Must be called before any other GLPI operation.
 */
async function initSession() {
  const res = await fetch(`${GLPI_API_BASE}/initSession`, {
    method: 'GET',
    headers: {
      'App-Token': GLPI_APP_TOKEN,
      'Authorization': `user_token ${GLPI_USER_TOKEN}`,
      'Content-Type': 'application/json',
    },
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GLPI initSession failed (${res.status}): ${text}`);
  }

  const data = await res.json();
  return data.session_token;
}

/**
 * Kill a GLPI session.
 */
async function killSession(sessionToken) {
  try {
    await fetch(`${GLPI_API_BASE}/killSession`, {
      method: 'GET',
      headers: {
        'App-Token': GLPI_APP_TOKEN,
        'Session-Token': sessionToken,
      },
    });
  } catch {
    // Best effort — don't throw on session cleanup failure
  }
}

/**
 * Make an authenticated GLPI API request.
 */
async function glpiRequest(sessionToken, method, path, body = null) {
  const headers = {
    'App-Token': GLPI_APP_TOKEN,
    'Session-Token': sessionToken,
    'Content-Type': 'application/json',
  };

  const options = { method, headers };
  if (body) options.body = JSON.stringify(body);

  const res = await fetch(`${GLPI_API_BASE}${path}`, options);

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GLPI ${method} ${path} failed (${res.status}): ${text}`);
  }

  return res.json();
}

// ─── GLPI Entity Mapping ──────────────────────────────────────────────
// Maps VEMIO tenant slugs to GLPI entity IDs
// From handoff doc: entity 4 → VE HQ, entity 18 → AIA
const ENTITY_MAP = {
  'vinay-hq': 4,
  'aia-engineering': 18,
};

// GLPI priority mapping from VEMIO severity
const SEVERITY_TO_PRIORITY = {
  critical: 5, // Very High
  high: 4,     // High
  medium: 3,   // Medium
  low: 2,      // Low
};

// GLPI category for VEMIO alerts (adjust if you have a specific category)
const DEFAULT_ITIL_CATEGORY = 0;

/**
 * Create a GLPI ticket for an alert.
 *
 * @param {Object} options
 * @param {string} options.title - Ticket title
 * @param {string} options.description - Ticket body (HTML)
 * @param {string} options.severity - VEMIO severity (critical|high|medium|low)
 * @param {string} options.tenantSlug - Tenant slug for entity mapping
 * @param {string} options.alertType - Alert type (device_down, sla_breach, bcs_drop)
 * @param {string} [options.deviceName] - Device name for context
 * @param {string} [options.siteName] - Site name for context
 * @returns {Promise<{ ticketId: number, ticketUrl: string }>}
 */
export async function createGLPITicket({
  title,
  description,
  severity,
  tenantSlug,
  alertType,
  deviceName,
  siteName,
}) {
  if (!GLPI_APP_TOKEN || !GLPI_USER_TOKEN) {
    console.warn('[GLPI] Missing tokens — skipping ticket creation');
    return null;
  }

  let sessionToken;
  try {
    sessionToken = await initSession();

    const entityId = ENTITY_MAP[tenantSlug] || 0;
    const priority = SEVERITY_TO_PRIORITY[severity] || 3;

    // Build description HTML
    const descHtml = `
      <div style="font-family: sans-serif; font-size: 13px;">
        <p><strong>VEMIO™ Alert — Auto-created ticket</strong></p>
        <table style="border-collapse: collapse; margin: 10px 0;">
          <tr><td style="padding: 4px 12px 4px 0; color: #666;">Alert Type</td><td>${alertType?.replace(/_/g, ' ') || '—'}</td></tr>
          <tr><td style="padding: 4px 12px 4px 0; color: #666;">Severity</td><td><strong style="text-transform: uppercase;">${severity}</strong></td></tr>
          ${deviceName ? `<tr><td style="padding: 4px 12px 4px 0; color: #666;">Device</td><td>${deviceName}</td></tr>` : ''}
          ${siteName ? `<tr><td style="padding: 4px 12px 4px 0; color: #666;">Site</td><td>${siteName}</td></tr>` : ''}
        </table>
        <hr style="border: none; border-top: 1px solid #eee; margin: 12px 0;">
        ${description || '<p>No additional details.</p>'}
        <p style="color: #999; font-size: 11px; margin-top: 16px;">
          Generated by VEMIO™ Managed Network Intelligence Platform
        </p>
      </div>
    `.trim();

    const ticketData = {
      input: {
        name: title,
        content: descHtml,
        priority,
        entities_id: entityId,
        type: 1, // Incident
        status: 2, // Assigned
        urgency: priority,
        impact: priority >= 4 ? 4 : 3,
        itilcategories_id: DEFAULT_ITIL_CATEGORY,
      },
    };

    const result = await glpiRequest(sessionToken, 'POST', '/Ticket', ticketData);
    const ticketId = result.id;

    console.log(`[GLPI] Created ticket #${ticketId} for alert: ${title}`);

    return {
      ticketId,
      ticketUrl: `https://techsupport.vinayenterprises.co.in/front/ticket.form.php?id=${ticketId}`,
    };
  } catch (err) {
    console.error('[GLPI] Failed to create ticket:', err.message);
    return null;
  } finally {
    if (sessionToken) await killSession(sessionToken);
  }
}

/**
 * Add a followup note to an existing GLPI ticket.
 */
export async function addGLPIFollowup(ticketId, content) {
  if (!GLPI_APP_TOKEN || !GLPI_USER_TOKEN || !ticketId) return null;

  let sessionToken;
  try {
    sessionToken = await initSession();

    const result = await glpiRequest(sessionToken, 'POST', '/Ticket/' + ticketId + '/ITILFollowup', {
      input: {
        itemtype: 'Ticket',
        items_id: ticketId,
        content: `<div style="font-family: sans-serif; font-size: 13px;">${content}</div>`,
        is_private: 0,
      },
    });

    console.log(`[GLPI] Added followup to ticket #${ticketId}`);
    return result;
  } catch (err) {
    console.error(`[GLPI] Failed to add followup to #${ticketId}:`, err.message);
    return null;
  } finally {
    if (sessionToken) await killSession(sessionToken);
  }
}

/**
 * Close/solve a GLPI ticket with resolution notes.
 */
export async function closeGLPITicket(ticketId, resolutionNote) {
  if (!GLPI_APP_TOKEN || !GLPI_USER_TOKEN || !ticketId) return null;

  let sessionToken;
  try {
    sessionToken = await initSession();

    // Add solution
    await glpiRequest(sessionToken, 'POST', '/Ticket/' + ticketId + '/ITILSolution', {
      input: {
        itemtype: 'Ticket',
        items_id: ticketId,
        content: `<div style="font-family: sans-serif; font-size: 13px;">${resolutionNote}</div>`,
        status: 5, // Solved
      },
    });

    console.log(`[GLPI] Closed ticket #${ticketId}`);
    return true;
  } catch (err) {
    console.error(`[GLPI] Failed to close #${ticketId}:`, err.message);
    return null;
  } finally {
    if (sessionToken) await killSession(sessionToken);
  }
}